linters:
  fast: false
  enable-all: true
  disable:
    - gomnd
    - gochecknoglobals
    - testpackage
    - paralleltest
    - nolintlint
    - cyclop
    - varnamelen
    - exhaustruct
    - nonamedreturns
    - depguard
    - mnd
    - copyloopvar
    - intrange
    - revive

    # deprecated
    - execinquery
