name: Test
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        go-version: [oldstable, stable]
        os: [ubuntu-latest, macos-latest, windows-latest, macos-14]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - run: go version
      - run: go test -v -cover -shuffle=on ./...
      - run: go test -v -cover -shuffle=on -race ./...

      - name: Send coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          flag-name: Go-${{ matrix.os }}-${{ matrix.go-version }}
          parallel: true

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: shogo82148/actions-goveralls@v1
        with:
          parallel-finished: true
